In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [ ]:
#converting 1D to 2D array
import numpy as np
arr=np.array([3,5,7,9,12,15,18,22])
print(arr)
arr1=(arr[1:6])
print(arr1)
arr2=arr.reshape(2,4)
print('convert 1D array to 2D array')
print('2D array is:',arr2)


[ 3  5  7  9 12 15 18 22]
[ 5  7  9 12 15]
convert 1D array to 2D array
2D array is: [[ 3  5  7  9]
 [12 15 18 22]]


In [ ]:
#slicing 3rd value to end
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8])
print('slicing 3rd value to end')
print(arr[3:])

slicing 3rd value to end
[4 5 6 7 8]


In [ ]:
#slice 0 to 4 index
import numpy as np
arr=np.array([1,45,3,4,14,6,7,8])
print('slice 0 to 4 index')
print(arr[:6])

slice 0 to 4 index
[ 1 45  3  4 14  6]


In [ ]:
#use stetp value using start and end value is empty
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8])
print('use step value using start and end value is empty')
print(arr[::3])

use step value using start and end value is empty
[1 4 7]


In [ ]:
#use slicing with interval input
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8])
print('use slicing with interval input')
print(arr[2::3])

use slicing with interval input
[3 6]


In [ ]:
#use slicing a 2D array
import numpy as np
arr=np.array([[3,5,7,9],[11,15,18,22]])
print('use slicing a 2D array')
print(' slicing with 2D array is:',arr[1,1:3])

use slicing a 2D array
 slicing with 2D array is: [15 18]


In [ ]:
#slicing 3D array
import numpy as np
arr=np.array([[[3,5,7,9],[11,15,18,22,],[24,28,30,32]]])
print('slicing 3D arrray')
print('slicing with 3D array:',arr[0,1,0:2])

slicing 3D arrray
slicing with 3D array: [11 15]


In [ ]:
#find the data type of an array (arr1,arr2,arr3)
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr3=np.array([[3,5,6],[2,4,8],[1,9,5]])
print('datatype of array')
print('datatype of array1',arr1.dtype)
print('datatype of array2',arr2.dtype)
print('datatype of array3',arr3.dtype)

datatype of array
datatype of array1 int64
datatype of array2 int64
datatype of array3 int64


In [ ]:
#reverse of the data
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,3,9,0,23,45,89])
res=(arr[::-1])
print('reverse of the data:',res)

reverse of the data: [89 45 23  0  9  3  8  7  6  5  4  3  2  1]


In [ ]:
#use concatenate()to join two arrays
import numpy as np
arr=np.array([1,2,3])
arr1=np.array([4,5,6])
con=np.concatenate((arr,arr1))
print('concatenating two arrays')
print('conatenate arrays:',con)


concatenating two arrays
conatenate arrays: [1 2 3 4 5 6]


In [ ]:
#use conacatenate()with axis=1
import numpy as np
arr=np.array([[1,2,3,],[4,5,7]])
arr1=np.array([[11,15,18],[17,18,10]])
con=np.concatenate((arr,arr1),axis=1)
print('conatenate with axis')
print(con)

conatenate with axis
[[ 1  2  3 11 15 18]
 [ 4  5  7 17 18 10]]
